apiVersion: v1
kind: Pod
metadata:
  name: simple-webserver-pod
spec:
  containers:
    - name: simple-webserver-v2
      image: maximikuznetsov/simple-webserver:latest
      ports:
        - containerPort: 8000
